/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetpharmacie;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.File;
import java.io.FileInputStream;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;
import java.io.ByteArrayOutputStream;
import java.io.ObjectOutputStream;
import java.io.Serializable;

/**
 *
 * @author user
 */
public class Produit extends javax.swing.JInternalFrame {

    File fichier, fichiers;
    Connection c;
    ResultSet res;
    Statement st;
    PreparedStatement pt;
    java.util.Date datef,datee;
    java.sql.Date fabrication,expiration;
    String caracteristique;
    public Produit() {
        initComponents();
               
          try{
        Class.forName("org.postgresql.Driver");    
        c =DriverManager.getConnection("jdbc:postgresql://localhost:5432/DBpharma","postgres", "123456");
        txtnom.requestFocus();
        
        selectProduit();
        combobox();
        recupererID();
        
        }catch(Exception e){        
         JOptionPane.showMessageDialog(this,"Erreur de connextion!","Authentification",JOptionPane.ERROR_MESSAGE);
         e.printStackTrace();
        }
          
           
    }
     public void selectProduit(){
        try{
        st = c.createStatement();
        res = st.executeQuery("select * from produit");
        tableproduit.setModel(DbUtils.resultSetToTableModel(res));
        }catch(SQLException e)
        {
            e.printStackTrace();
        }
}
     
      public void recupererID(){
         try{
        String sql = "select max(nump)+1 as IDsuivi from produit";
        pt = c.prepareStatement(sql);
        res = pt.executeQuery();
        while (res.next()){
            int ID = res.getInt("IDsuivi");
            txtid.setText(String.valueOf(ID));
        }
        txtid.setEnabled(false);
       }catch(Exception e){
            JOptionPane.showMessageDialog(this,"Erreur de recuperer ID!","Combobox",JOptionPane.ERROR_MESSAGE);
           e.printStackTrace();
       }
    }
     public void combobox(){
         try{
        String sql = "select * from fornisseur ";
        pt = c.prepareStatement(sql);
        res = pt.executeQuery();
        while (res.next()){
            String name = res.getString("entreprise");
            cmbentreprise.addItem(name);
        }
       }catch(Exception e){
           JOptionPane.showMessageDialog(this,"Erreur de lecture Combobox!","Combobox",JOptionPane.ERROR_MESSAGE);
           e.printStackTrace();
       }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtnom = new javax.swing.JTextField();
        txtquantite = new javax.swing.JTextField();
        txtprix = new javax.swing.JTextField();
        lblimage = new javax.swing.JLabel();
        cmbentreprise = new javax.swing.JComboBox<>();
        btnimage = new javax.swing.JButton();
        btnajouter = new javax.swing.JButton();
        btnsupprimer = new javax.swing.JButton();
        btnmodifier = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableproduit = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        datefabrication = new com.toedter.calendar.JDateChooser();
        dateexpiration = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        lblcaracteristique = new javax.swing.JLabel();
        btnvider = new javax.swing.JButton();
        rbordonnance = new javax.swing.JRadioButton();
        rbsans = new javax.swing.JRadioButton();
        btnrechercher = new javax.swing.JButton();

        setBorder(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(0, 102, 0));
        jPanel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(133, 200, 42));
        jLabel1.setText("Nom :");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 79, 30));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(133, 200, 42));
        jLabel2.setText("Quantité :");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(133, 200, 42));
        jLabel3.setText("Prix :");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 79, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(133, 200, 42));
        jLabel4.setText("Image :");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(133, 200, 42));
        jLabel5.setText("Entreprise :");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 240, 110, 40));

        txtnom.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtnom.setForeground(new java.awt.Color(0, 102, 0));
        jPanel2.add(txtnom, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, 152, 41));

        txtquantite.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtquantite.setForeground(new java.awt.Color(0, 102, 0));
        jPanel2.add(txtquantite, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, 152, 41));

        txtprix.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtprix.setForeground(new java.awt.Color(0, 102, 0));
        jPanel2.add(txtprix, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 152, 41));

        lblimage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 0)));
        jPanel2.add(lblimage, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, 150, 90));

        cmbentreprise.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmbentreprise.setForeground(new java.awt.Color(133, 200, 42));
        jPanel2.add(cmbentreprise, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 240, 190, 40));

        btnimage.setBackground(new java.awt.Color(133, 200, 42));
        btnimage.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnimage.setForeground(new java.awt.Color(255, 255, 255));
        btnimage.setText("Charger image ");
        btnimage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnimageActionPerformed(evt);
            }
        });
        jPanel2.add(btnimage, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 310, 120, 30));

        btnajouter.setBackground(new java.awt.Color(49, 184, 191));
        btnajouter.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnajouter.setForeground(new java.awt.Color(255, 255, 255));
        btnajouter.setText("Ajouter");
        btnajouter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnajouterMouseClicked(evt);
            }
        });
        jPanel2.add(btnajouter, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 420, 152, 42));

        btnsupprimer.setBackground(new java.awt.Color(49, 184, 191));
        btnsupprimer.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnsupprimer.setForeground(new java.awt.Color(255, 255, 255));
        btnsupprimer.setText("Supprimer");
        btnsupprimer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnsupprimerMouseClicked(evt);
            }
        });
        jPanel2.add(btnsupprimer, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 420, 152, 42));

        btnmodifier.setBackground(new java.awt.Color(49, 184, 191));
        btnmodifier.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnmodifier.setForeground(new java.awt.Color(255, 255, 255));
        btnmodifier.setText("Modifier");
        btnmodifier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnmodifierMouseClicked(evt);
            }
        });
        jPanel2.add(btnmodifier, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 420, 152, 42));

        tableproduit.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tableproduit.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nom", "Quantité", "Prix", "Image", "Date Fabrication", "Date expiration", "Entreprise", "Caracteristique"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableproduit.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tableproduit.setRowHeight(25);
        tableproduit.setSelectionBackground(new java.awt.Color(188, 226, 142));
        tableproduit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableproduitMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableproduit);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 540, 790, 130));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(133, 200, 42));
        jLabel7.setText("Gestion des produits");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, 418, 39));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(133, 200, 42));
        jLabel8.setText("Liste des produits");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 480, 280, 38));
        jPanel2.add(datefabrication, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 110, 190, 40));
        jPanel2.add(dateexpiration, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 170, 190, 40));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(133, 200, 42));
        jLabel9.setText("Date fabrication : ");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 110, 150, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(133, 200, 42));
        jLabel10.setText("Date expiration : ");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 180, 140, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(133, 200, 42));
        jLabel6.setText("ID :");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 40, 30));

        txtid.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtid.setForeground(new java.awt.Color(0, 102, 0));
        jPanel2.add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 150, 40));

        lblcaracteristique.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblcaracteristique.setForeground(new java.awt.Color(133, 200, 42));
        lblcaracteristique.setText("Caractéristique :");
        jPanel2.add(lblcaracteristique, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 310, 140, 30));

        btnvider.setBackground(new java.awt.Color(49, 184, 191));
        btnvider.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnvider.setForeground(new java.awt.Color(255, 255, 255));
        btnvider.setText("Vider");
        btnvider.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnviderMouseClicked(evt);
            }
        });
        jPanel2.add(btnvider, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 420, 150, 40));

        rbordonnance.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rbordonnance);
        rbordonnance.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rbordonnance.setForeground(new java.awt.Color(133, 200, 42));
        rbordonnance.setText("Ordonnance");
        rbordonnance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbordonnanceActionPerformed(evt);
            }
        });
        jPanel2.add(rbordonnance, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 320, 160, 30));

        rbsans.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rbsans);
        rbsans.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rbsans.setForeground(new java.awt.Color(133, 200, 42));
        rbsans.setText("Sans ordonnance");
        rbsans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbsansActionPerformed(evt);
            }
        });
        jPanel2.add(rbsans, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 360, -1, 30));

        btnrechercher.setBackground(new java.awt.Color(49, 184, 191));
        btnrechercher.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnrechercher.setForeground(new java.awt.Color(255, 255, 255));
        btnrechercher.setText("Rechercher");
        btnrechercher.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnrechercherMouseClicked(evt);
            }
        });
        jPanel2.add(btnrechercher, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 490, 150, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1559, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 832, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnimageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnimageActionPerformed
        try{
             
             JFileChooser choixFichier = new JFileChooser();
             choixFichier.addChoosableFileFilter(new FileNameExtensionFilter("fichier images","jpeg","png"));
             choixFichier.showDialog(this,"choisir une image");
             fichier=choixFichier.getSelectedFile();
             BufferedImage image1=ImageIO.read(fichier); 
             Image img1=image1.getScaledInstance(lblimage.getWidth(),lblimage.getHeight(),Image.SCALE_SMOOTH);
             lblimage.setIcon(new ImageIcon(img1));
             
             
            }catch(Exception e){
                JOptionPane.showConfirmDialog(this,"erreur lecture image!");
            }
    }//GEN-LAST:event_btnimageActionPerformed

    private void btnajouterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnajouterMouseClicked
        datef = datefabrication.getDate();
        fabrication = new java.sql.Date(datef.getTime());
        datee = dateexpiration.getDate();
        expiration = new java.sql.Date(datee.getTime());
        try{
            PreparedStatement pt = c.prepareStatement("insert into produit values (?,?,?,?,?,?,?,?,?)");
            pt.setInt(1, Integer.valueOf(txtid.getText()));
            pt.setString(2, txtnom.getText());
            pt.setInt(3, Integer.valueOf(txtquantite.getText()));
            pt.setInt(4, Integer.valueOf(txtprix.getText()));
            pt.setBinaryStream(5, new FileInputStream(fichier));
            pt.setDate(6, fabrication);
            pt.setDate(7, expiration);
            pt.setString(8, cmbentreprise.getSelectedItem().toString());
            pt.setString(9, caracteristique);
            int row = pt.executeUpdate();
            JOptionPane.showMessageDialog(this,"un produit à été ajouté!","Ajout Produits",JOptionPane.PLAIN_MESSAGE);
            txtid.setText("");
            txtnom.setText("");
            txtquantite.setText("");
            txtprix.setText("");
            lblimage.setIcon(null);
            datefabrication.setDate(null);
            dateexpiration.setDate(null);
            cmbentreprise.setSelectedIndex(0);
            buttonGroup1.clearSelection();
            txtid.requestFocus();
            btnajouter.setEnabled(true);
            selectProduit();
        }catch(SQLException e){
            e.printStackTrace();
        }catch(Exception e){
            JOptionPane.showMessageDialog(this,"Erreur ajout produit!","Ajout Produits",JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnajouterMouseClicked

    private void btnsupprimerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsupprimerMouseClicked
        if(txtid.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "entez ID de produit qui va etre supprimé");
        }
        else{
            try{
                String Id = txtid.getText();
                String query = "delete from produit where nump="+Id;
                Statement st = c.createStatement();
                st.executeUpdate(query);
                selectProduit();
                JOptionPane.showMessageDialog(this,"un produit à été supprimé!","Suppression Produits",JOptionPane.PLAIN_MESSAGE);
                txtid.setText("");
                txtnom.setText("");
                txtquantite.setText("");
                txtprix.setText("");
                lblimage.setIcon(null);
                datefabrication.setDate(null);
                dateexpiration.setDate(null);
                cmbentreprise.setSelectedIndex(0);
                buttonGroup1.clearSelection();
                txtid.requestFocus();
                btnajouter.setEnabled(true);
            }catch(SQLException e){
                JOptionPane.showMessageDialog(this,"Erreur de suppression produit!","Supression Produits",JOptionPane.ERROR_MESSAGE);
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnsupprimerMouseClicked

    private void btnmodifierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnmodifierMouseClicked
        if(txtid.getText().isEmpty() || txtnom.getText().isEmpty() || txtquantite.getText().isEmpty() || txtprix.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "des informations qui manquent");
        }else
        {
            try{
                DefaultTableModel model=(DefaultTableModel)tableproduit.getModel();
                int  selected=tableproduit.getSelectedRow();
                int    id=Integer.parseInt(model.getValueAt(selected,0).toString());

                datef = datefabrication.getDate();
                fabrication = new java.sql.Date(datef.getTime());
                datee = dateexpiration.getDate();
                expiration = new java.sql.Date(datee.getTime());//,imagep = "+lblimage.getText()+"
                pt = c.prepareStatement("UPDATE  produit  SET nomp=?,quantitep=?,prixp=?,imagep=?,datef=?,datee=?,entrepeise=?,caracteristique=? WHERE nump=?");
                pt.setString(1,txtnom.getText());
                pt.setInt(2,Integer.valueOf(txtquantite.getText()));
                pt.setInt(3,Integer.valueOf(txtprix.getText()));
                pt.setBinaryStream(4, new FileInputStream(fichier));
                pt.setDate(5,fabrication);
                pt.setDate(6,expiration);
                pt.setString(7,cmbentreprise.getSelectedItem().toString());
                pt.setString(8, caracteristique);
                pt.setInt(9,id);
                pt.executeUpdate();
                /*String updateQuery= "update produit set nomp = '"+txtnom.getText()+"' ,quantitep = "+txtquantite.getText()+",prixp = "+txtprix.getText()+",datef = '"+fabrication+"',datee = '"+expiration+"'  where nump = " +txtid.getText() ;
                Statement st = c.createStatement();
                st.executeUpdate(updateQuery);*/
                JOptionPane.showMessageDialog(this,"un produit à été modifié!","Modification Produits",JOptionPane.PLAIN_MESSAGE);

                txtid.setText("");
                txtnom.setText("");
                txtquantite.setText("");
                txtprix.setText("");
                lblimage.setIcon(null);
                datefabrication.setDate(null);
                dateexpiration.setDate(null);
                cmbentreprise.setSelectedIndex(0);
                buttonGroup1.clearSelection();

                txtid.requestFocus();
                btnajouter.setEnabled(true);
            }catch(Exception e){
                JOptionPane.showMessageDialog(this,"Erreur de modification produit!","Modification Produits",JOptionPane.ERROR_MESSAGE);
                e.printStackTrace();
            }
            selectProduit();

        }

        /*   txtname.setText("");
        txttel.setText("");
        txtadress.setText("");
        txtent.setText("");
        txtname.requestFocus();
        Load();
        jButton2.setEnabled(true);
        }catch(Exception e){
            JOptionPane.showMessageDialog(this,"erreur de modification Personnel ");
            e.printStackTrace();
        }*/
    }//GEN-LAST:event_btnmodifierMouseClicked

    private void tableproduitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableproduitMouseClicked
        try{
            DefaultTableModel model = (DefaultTableModel)tableproduit.getModel();
            int Myindex = tableproduit.getSelectedRow();
            txtid.setText(model.getValueAt(Myindex, 0).toString());
            txtnom.setText(model.getValueAt(Myindex, 1).toString());
            txtquantite.setText(model.getValueAt(Myindex, 2).toString());
            txtprix.setText(model.getValueAt(Myindex, 3).toString());
            byte[] b = (byte[])model.getValueAt(Myindex, 4);
            BufferedImage img1 = ImageIO.read(new ByteArrayInputStream(b));
            lblimage.setIcon( new ImageIcon(img1.getScaledInstance(lblimage.getWidth(),lblimage.getHeight(),Image.SCALE_SMOOTH)));
            Date fab = new SimpleDateFormat("dd-MM-yyyy").parse(model.getValueAt(Myindex, 5).toString());
            datefabrication.setDate(fab);
            Date exp = new SimpleDateFormat("dd-MM-yyyy").parse(model.getValueAt(Myindex, 6).toString());
            dateexpiration.setDate(exp);
            cmbentreprise.setSelectedItem(model.getValueAt(Myindex, 7).toString());
            caracteristique = model.getValueAt(Myindex, 8).toString();
            if(caracteristique.equals("true"))
            {
                rbordonnance.setSelected(true);

            }
            else{
                rbsans.setSelected(true);

            }
            btnajouter.setEnabled(false);
        }catch (Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_tableproduitMouseClicked

    private void btnviderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnviderMouseClicked
        
        txtnom.setText("");
        txtquantite.setText("");
        txtprix.setText("");
        lblimage.setIcon(null);
        datefabrication.setDate(null);
        dateexpiration.setDate(null);
        cmbentreprise.setSelectedIndex(0);
        buttonGroup1.clearSelection();
        txtnom.requestFocus();
        btnajouter.setEnabled(true);
        recupererID();

    }//GEN-LAST:event_btnviderMouseClicked

    private void rbordonnanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbordonnanceActionPerformed
        caracteristique = "true";
    }//GEN-LAST:event_rbordonnanceActionPerformed

    private void rbsansActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbsansActionPerformed
        caracteristique = "false";
    }//GEN-LAST:event_rbsansActionPerformed

    private void btnrechercherMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnrechercherMouseClicked
        int  id = Integer.valueOf(txtid.getText());
        for (int i = 0; i < tableproduit.getRowCount(); i++) {
            if (tableproduit.getValueAt(i, 0).equals(id)) {
                tableproduit.setRowSelectionInterval(i, i);

            }

        }
        txtid.setText("");
    }//GEN-LAST:event_btnrechercherMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnajouter;
    private javax.swing.JButton btnimage;
    private javax.swing.JButton btnmodifier;
    private javax.swing.JButton btnrechercher;
    private javax.swing.JButton btnsupprimer;
    private javax.swing.JButton btnvider;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cmbentreprise;
    private com.toedter.calendar.JDateChooser dateexpiration;
    private com.toedter.calendar.JDateChooser datefabrication;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblcaracteristique;
    private javax.swing.JLabel lblimage;
    private javax.swing.JRadioButton rbordonnance;
    private javax.swing.JRadioButton rbsans;
    private javax.swing.JTable tableproduit;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtnom;
    private javax.swing.JTextField txtprix;
    private javax.swing.JTextField txtquantite;
    // End of variables declaration//GEN-END:variables
}
