/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetpharmacie;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author user
 */
public class Vente extends javax.swing.JInternalFrame {

     Connection c;
    ResultSet res;
    Statement st;
    PreparedStatement pt;
    String caracteristique;
    java.sql.Date dateF;

    public Vente() {
        initComponents();
        
         try{
        Class.forName("org.postgresql.Driver");    
        c =DriverManager.getConnection("jdbc:postgresql://localhost:5432/DBpharma","postgres", "123456");
        }catch(Exception e){        
         JOptionPane.showMessageDialog(this,"Erreur de connextion!");
          
         e.printStackTrace();
        }
        selectProduit();
        showDte();
        recupererID();
        btnClient.setEnabled(false);
    }
     public void recupererID(){
         try{
        String sql = "select max(numv)+1 as IDsuivi from vente";
        pt = c.prepareStatement(sql);
        res = pt.executeQuery();
        while (res.next()){
            int ID = res.getInt("IDsuivi");
            txtid.setText(String.valueOf(ID));
        }
        txtid.setEnabled(false);
       }catch(Exception e){
            JOptionPane.showMessageDialog(this,"Erreur de recuperer ID!","Combobox",JOptionPane.ERROR_MESSAGE);
           e.printStackTrace();
       }
    }
    
     public void showDte(){
        Date d = new Date();
        SimpleDateFormat s = new SimpleDateFormat("dd-MM-yyyy");
        lbldate.setText(s.format(d));
    }

    public void selectProduit(){
        try{
        
        st = c.createStatement();
        res = st.executeQuery("select * from produit");
        tableproduit.setModel(DbUtils.resultSetToTableModel(res));
        }catch(SQLException e)
        {
            e.printStackTrace();
        }
}
    public void update(){
        int newqt;
        newqt = oldqt - Integer.valueOf(txtquantite.getText());
        try{ 
                String updateQuery= " update produit set quantitep = "+newqt+""+ " where nump = " +prodId ;
                Statement st = c.createStatement();
                st.executeUpdate(updateQuery);
                JOptionPane.showMessageDialog(this, "quantite a été modifié");
            }catch(Exception e){
              JOptionPane.showMessageDialog(this, "erreur de mise a jour");
             e.printStackTrace();
            }
        selectProduit();
        
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtnom = new javax.swing.JTextField();
        btnAjouter = new javax.swing.JButton();
        btnImprimer = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtquantite = new javax.swing.JTextField();
        txtid = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableproduit = new javax.swing.JTable();
        btnVider = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        lbldate = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnClient = new javax.swing.JButton();

        setBorder(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(133, 200, 42));
        jLabel1.setText("ID");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(90, 170, 79, 30);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(133, 200, 42));
        jLabel2.setText("Facture");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(500, 420, 110, 30);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(133, 200, 42));
        jLabel3.setText("nom produit");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(70, 220, 130, 30);

        txtnom.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtnom.setForeground(new java.awt.Color(0, 102, 0));
        jPanel2.add(txtnom);
        txtnom.setBounds(210, 220, 140, 33);

        btnAjouter.setBackground(new java.awt.Color(49, 184, 191));
        btnAjouter.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnAjouter.setForeground(new java.awt.Color(255, 255, 255));
        btnAjouter.setText("Ajouter facture");
        btnAjouter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAjouterMouseClicked(evt);
            }
        });
        btnAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjouterActionPerformed(evt);
            }
        });
        jPanel2.add(btnAjouter);
        btnAjouter.setBounds(410, 350, 180, 50);

        btnImprimer.setBackground(new java.awt.Color(49, 184, 191));
        btnImprimer.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnImprimer.setForeground(new java.awt.Color(255, 255, 255));
        btnImprimer.setText("Imprimer");
        btnImprimer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnImprimerMouseClicked(evt);
            }
        });
        btnImprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimerActionPerformed(evt);
            }
        });
        jPanel2.add(btnImprimer);
        btnImprimer.setBounds(480, 630, 130, 30);

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(133, 200, 42));
        jLabel9.setText("Gérer les ventes et facture");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(360, 30, 340, 46);

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(133, 200, 42));
        jLabel11.setText("Quantité");
        jLabel11.setToolTipText("");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(70, 270, 90, 41);

        txtquantite.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtquantite.setForeground(new java.awt.Color(0, 102, 0));
        jPanel2.add(txtquantite);
        txtquantite.setBounds(210, 270, 140, 33);

        txtid.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtid.setForeground(new java.awt.Color(0, 102, 0));
        jPanel2.add(txtid);
        txtid.setBounds(210, 170, 140, 33);

        tableproduit.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tableproduit.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nom", "Quantité", "Prix", "Image", "Date Fabrication", "Date expiration", "Entreprise", "Caractéristique"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableproduit.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tableproduit.setRowHeight(25);
        tableproduit.setSelectionBackground(new java.awt.Color(188, 226, 142));
        tableproduit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableproduitMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableproduit);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(370, 170, 550, 140);

        btnVider.setBackground(new java.awt.Color(49, 184, 191));
        btnVider.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnVider.setForeground(new java.awt.Color(255, 255, 255));
        btnVider.setText("Vider");
        btnVider.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnViderMouseClicked(evt);
            }
        });
        btnVider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViderActionPerformed(evt);
            }
        });
        jPanel2.add(btnVider);
        btnVider.setBounds(780, 350, 150, 50);

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Monospaced", 1, 16)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("***********************PharmaSalma_Ahlam***********************");
        jScrollPane2.setViewportView(jTextArea1);

        jPanel2.add(jScrollPane2);
        jScrollPane2.setBounds(220, 460, 640, 160);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(49, 184, 191));
        jLabel4.setText("Liste des produits");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(540, 110, 180, 46);

        lbldate.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        lbldate.setForeground(new java.awt.Color(183, 189, 192));
        lbldate.setText("Date");
        jPanel2.add(lbldate);
        lbldate.setBounds(790, 40, 190, 21);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(183, 189, 192));
        jLabel6.setText("Vente");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(90, 40, 70, 21);

        btnClient.setBackground(new java.awt.Color(133, 200, 42));
        btnClient.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnClient.setForeground(new java.awt.Color(255, 255, 255));
        btnClient.setText("Ajouter clienrt");
        btnClient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClientMouseClicked(evt);
            }
        });
        jPanel2.add(btnClient);
        btnClient.setBounds(80, 350, 150, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1620, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 845, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 int i=0,prix,prodId,oldqt;
    private void btnAjouterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAjouterMouseClicked

        if(txtnom.getText().isEmpty() || txtquantite.getText().isEmpty() ){
            JOptionPane.showMessageDialog(this,"des informations qui manquent");
        }else{

            i++;
            update();
            if(i == 1){
                jTextArea1.setText(jTextArea1.getText()+"***********************PharmaSalma_Ahlam***********************\n"
                    +"\t ID      Produit      Quantité      prix      Total\n\t"
                    +" "+ i +"      "+txtnom.getText()+"      "+txtquantite.getText()+"            "+prix+"            "+Integer.valueOf(txtquantite.getText())*prix+"\n          ");
            }else{
                jTextArea1.setText(jTextArea1.getText()+i+"      "+txtnom.getText()+"      "+txtquantite.getText()+"      "+prix+"      "+Integer.valueOf(txtquantite.getText())*prix);
            }

            try{
                SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
                String strDate=lbldate.getText();
                dateF = new java.sql.Date(sdf.parse(strDate).getTime());

                PreparedStatement ptp = c.prepareStatement("insert into facture(nomf,quantitep,prix,prixTotale,datefa ) values (?,?,?,?,?)");
                ptp.setString(1, txtnom.getText());
                ptp.setInt(2, Integer.valueOf(txtquantite.getText()));
                ptp.setInt(3, prix);
                ptp.setInt(4, Integer.valueOf(txtquantite.getText())*prix);
                ptp.setDate(5,dateF);
                int row = ptp.executeUpdate();
                JOptionPane.showMessageDialog(this,"une facture a été ajouté");
                selectProduit();
            }catch(SQLException e){
                e.printStackTrace();
            }catch(Exception e){
                JOptionPane.showMessageDialog(this,"erreur d'ajouter facture  ");
                e.printStackTrace();
            }

            try{

                PreparedStatement pt = c.prepareStatement("insert into vente(nomp,quantitep) values (?,?)");
                //pt.setInt(1, Integer.valueOf(txtid.getText()));
                pt.setString(1, txtnom.getText());
                pt.setInt(2, Integer.valueOf(txtquantite.getText()));
                int row = pt.executeUpdate();
                JOptionPane.showMessageDialog(this,"une vente a été ajouté");
                txtid.setText("");
                txtnom.setText("");
                txtquantite.setText("");
                txtid.requestFocus();
                btnAjouter.setEnabled(false);
                selectProduit();
            }catch(SQLException e){
                e.printStackTrace();
            }catch(Exception e){
                JOptionPane.showMessageDialog(this,"erreur ajout vente ");
                e.printStackTrace();
            }

        }

    }//GEN-LAST:event_btnAjouterMouseClicked

    private void btnImprimerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnImprimerMouseClicked
        try{
            jTextArea1.print();
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnImprimerMouseClicked

    private void btnImprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnImprimerActionPerformed

    private void tableproduitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableproduitMouseClicked
        DefaultTableModel model = (DefaultTableModel)tableproduit.getModel();
        int Myindex = tableproduit.getSelectedRow();
        //txtid.setText(model.getValueAt(Myindex, 0).toString());
        prodId = Integer.valueOf(model.getValueAt(Myindex, 0).toString());
        txtnom.setText(model.getValueAt(Myindex, 1).toString());
        txtquantite.setText(model.getValueAt(Myindex, 2).toString());
        oldqt = Integer.valueOf(model.getValueAt(Myindex, 2).toString());
        prix = Integer.valueOf(model.getValueAt(Myindex, 3).toString());

        caracteristique = model.getValueAt(Myindex, 8).toString();
        if(caracteristique.equals("true")){
            btnClient.setEnabled(true);

        }else{
            btnClient.setEnabled(false);}

        if(oldqt==0){
            btnAjouter.setEnabled(false);
            JOptionPane.showMessageDialog(this,"le produit n'excite pas dans le stock");

        }else{
            btnAjouter.setEnabled(true);}
    }//GEN-LAST:event_tableproduitMouseClicked

    private void btnViderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViderMouseClicked
        txtnom.setText("");
        txtquantite.setText("");
        txtnom.requestFocus();
    }//GEN-LAST:event_btnViderMouseClicked

    private void btnViderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnViderActionPerformed

    private void btnClientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClientMouseClicked
        if(caracteristique.equals("true")){
         Client C=new Client();
        C.setVisible(true);
        
        }
        
       
    }//GEN-LAST:event_btnClientMouseClicked

    private void btnAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjouterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAjouterActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAjouter;
    private javax.swing.JButton btnClient;
    private javax.swing.JButton btnImprimer;
    private javax.swing.JButton btnVider;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lbldate;
    private javax.swing.JTable tableproduit;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtnom;
    private javax.swing.JTextField txtquantite;
    // End of variables declaration//GEN-END:variables
}
